name: nean_verg_s_application2
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  table_calendar: ^3.0.0
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.0.0
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  equatable: ^2.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto Slab
      fonts: 
        - asset: assets/fonts/RobotoSlabRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoSlabLight.ttf
          weight: 300
        - asset: assets/fonts/RobotoSlabSemiBold.ttf
          weight: 600
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Gothic A1
      fonts: 
        - asset: assets/fonts/GothicA1SemiBold.ttf
          weight: 600
